### ISSUE TITLE
Slim module for FA

### ISSUE THREAD

**Issue by derevandal** [mustardamus/nuxt-bulma-slim#3]
Hi, 

Have you thought about making a module like this but that would support the Font Awesome?

Thanks.

**Comment by mustardamus** [comment]
Hi André,

thanks for the request. You could actually achieve this by using the `additionalPaths` option and bundle the FontAwesome SCSS (https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/scss/fontawesome.scss), or just CSS, along with Bulma.

That should do the trick.

After I was done with this module I realized that you can do it with any CSS Framework, so maybe I'll develop a generic module that uses PurgeCSS in the way it does now. But currently I got a lot of work and will not be able to do so. Feel free to fork ;)
